# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('people', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
