# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_sets',
            name='slug',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
