# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group_sets_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_sets',
            old_name='people',
            new_name='users',
        ),
    ]
