# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_sets',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
