# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170419_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_group',
            name='avatar',
            field=models.ImageField(default=b'avatars/default.jpg', upload_to=b'avatars/'),
        ),
    ]
