# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rep',
            field=models.IntegerField(default=0),
        ),
    ]
