# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170423_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
