# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_image',
            field=models.ImageField(default=b'images/None/no-img.jpg', upload_to=b'images/'),
        ),
    ]
