# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170411_2130'),
        ('blog', '0004_post_new_image'),
    ]

