# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_group'),
    ]


