# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170412_1353'),
        ('blog', '0007_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
