# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170419_0211'),
        ('blog', '0011_auto_20170417_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='accounts.User_Group'),
        ),
    ]
