# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='new_image',
        ),
    ]
