# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_remove_post_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
