# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 21:15
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_auto_20170310_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FFFF00', max_length=10),
        ),
        migrations.AlterField(
            model_name='colors',
            name='third_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=10),
        ),
    ]
